backend:
  name: github
  repo: daredoes/redirection
  branch: cms

media_folder: static/assets
public_folder: assets

collections: # A list of collections the CMS should be able to edit
  name: "category"
  label: "Category"
  folder: "src/content/categories"
  fields:
    - {label: "Title", name: "title", widget: "string", tagname: "h1"}
    - {label: "Body", name: "body", widget: "markdown"}
