backend:
  name: github
  repo: daredoes/redirection
  branch: cms

media_folder: static/assets
public_folder: assets

collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Pages"
    files:
      - label: "Resume"
        name: "resume"
        file: "site/content/categories/_index.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "About Me", name: "body", widget: "markdown", required: false}
