backend:
  name: github
  repo: daredoes/redirection
  branch: cms

media_folder: static/assets
public_folder: assets

collections: # A list of collections the CMS should be able to edit
  - label: "Category"
    name: "category"
    folder: "src/content/categories"
    create: true
    fields:
        - {label: "Name", name: "title", widget: "string"}
  - label: "Item"
    name: "item"
    folder: "src/content/items"
    create: true
    fields:
        - {label: "Name", name: "title", widget: "string"}
        - {label: "Description", name: "body", widget: "markdown", required: false}
        - {label: "Path", name: "path", widget: "string"}
        - {label: "URL", name: "url", widget: "string"}
        - {label: "Status", name: "status", widget: "select", options: ["200", "301", "303"], default: "200"}
        - {label: "Public", name: "public", widget: "boolean", default: true}
        - {label: "Enabled", name: "enabled", widget: "boolean", default: true}
        - label: "Category"
          name: "category"
          widget: "relation"
          collection: "category"
          searchFields: ["title"]
          valueField: "title"
          required: false
